-- Table for incoming/outgoing Instagram messages
CREATE TABLE IF NOT EXISTS instagram_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instagram_id text NOT NULL,
  direction text NOT NULL,
  body text,
  raw jsonb,
  created_at timestamp with time zone DEFAULT now()
);
