import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Sidebar from './components/Sidebar'
import ThemeToggle from './components/ThemeToggle'
import { Providers } from './providers'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Make the root layout dynamic so auth header updates immediately after login/logout
export const dynamic = 'force-dynamic'
export const revalidate = 0

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <Providers>
          <div className="flex min-h-screen">
            <Sidebar />
            <main className="flex-1 bg-neutral-50 dark:bg-neutral-950 overflow-auto relative">
              {children}
              {/* Floating ThemeToggle Button, weiter links */}
              <div className="fixed bottom-6 right-3 z-50">
                <ThemeToggle />
              </div>
            </main>
          </div>
        </Providers>
      </body>
    </html>
  )
}
